### ISSUE TITLE
Cannot read property 'readdir' of undefined

### ISSUE THREAD

**Issue by soareswallace** [generative-music/generative.fm#98]
After following the readme installation procedure I was getting this error: 

`/Users/wallace/Github/generative.fm/webpack.config.js:83
  .readdir(path.resolve('./src'))
  ^

TypeError: Cannot read property 'readdir' of undefined
    at Object.<anonymous> (/Users/wallace/Github/generative.fm/webpack.config.js:83:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at WEBPACK_OPTIONS (/Users/wallace/Github/generative.fm/node_modules/webpack-cli/bin/convert-argv.js:115:13)
    at requireConfig (/Users/wallace/Github/generative.fm/node_modules/webpack-cli/bin/convert-argv.js:117:6)`

**Comment by metalex9** [comment]
What version of Node are you using? I'll bet you're on one that doesn't have the [`fs.promises` API](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api), which is why it's undefined. You probably need to be on Node >= 10, and I ought to add that detail to the readme.

**Comment by soareswallace** [comment]
I will check that is probably below 10. Once I confirm I will close this issue! 👍🏼

**Comment by soareswallace** [comment]
Yeap, version 6.9.0

**Comment by soareswallace** [comment]
But @metalex9 how can I solve this in macOS? according to npm the latest version running on macOS is 6.9.0
